# Generated by Django 5.2.17 on 2026-09-07 21:56

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="task_board_avatars/%Y/%m/",
                        verbose_name="Аватар доски",
                    ),
                ),
                (
                    "access_scope",
                    models.CharField(
                        choices=[
                            ("all", "Для всех"),
                            ("private", "Для себя"),
                            ("restricted", "Выборочно"),
                        ],
                        default="private",
                        max_length=16,
                        verbose_name="Доступ",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Архивная"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nb_created_task_boards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nb_task_boards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доска задач",
                "verbose_name_plural": "Доски задач",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=32, verbose_name="Цвет"),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False, verbose_name="Финальная колонка"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Архивная"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="nadein_board.taskboard",
                        verbose_name="Доска",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcolumns",
                        to="nadein_board.taskcolumn",
                        verbose_name="Родительская колонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Колонка задач",
                "verbose_name_plural": "Колонки задач",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskColumnRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=32, verbose_name="Цвет"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="nadein_board.taskcolumn",
                        verbose_name="Основная колонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дорожка колонки",
                "verbose_name_plural": "Дорожки колонок",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("critical", "Критический"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nb_assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nb_created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nb_participating_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="nadein_board.taskboard",
                        verbose_name="Доска",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="nadein_board.taskcolumn",
                        verbose_name="Колонка",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="nadein_board.taskcolumnrow",
                        verbose_name="Дорожка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["position", "-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="nadein_board.task",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Название")),
                (
                    "color",
                    models.CharField(
                        default="#38bdf8", max_length=32, verbose_name="Цвет"
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="nadein_board.taskboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метка задачи",
                "verbose_name_plural": "Метки задач",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                to="nadein_board.tasklabel",
                verbose_name="Метки",
            ),
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="task_attachments/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="Размер файла (байты)"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="nadein_board.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nb_uploaded_task_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение задачи",
                "verbose_name_plural": "Вложения задач",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="nadein_boar_task_id_64a680_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Пункт")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Выполнен"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Выполнен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nb_completed_task_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отметил выполненным",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nb_created_task_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="nadein_board.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт чек-листа задачи",
                "verbose_name_plural": "Пункты чек-листа задач",
                "ordering": ["position", "id"],
                "indexes": [
                    models.Index(
                        fields=["task", "position"],
                        name="nadein_boar_task_id_5c5d8a_idx",
                    ),
                    models.Index(
                        fields=["task", "is_completed"],
                        name="nadein_boar_task_id_72d3fa_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taskcolumn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("board", "name"),
                name="nb_uniq_task_top_column_board_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcolumn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="nb_uniq_task_subcolumn_parent_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcolumn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_done", True), ("parent__isnull", True)),
                fields=("board",),
                name="nb_uniq_task_done_column_per_board",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcolumnrow",
            constraint=models.UniqueConstraint(
                fields=("column", "name"), name="nb_uniq_task_column_row_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklabel",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("board"),
                name="nb_uniq_task_label_name_ci",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["board", "column", "row", "position"],
                name="nadein_boar_board_i_dbb132_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "due_date"], name="nadein_boar_assigne_09f21c_idx"
            ),
        ),
    ]
