# Generated by Django 5.2.17 on 2026-09-07 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nadein_board", "0002_taskcover"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="taskcover",
            name="kind",
            field=models.CharField(
                choices=[
                    ("attachment", "Файл"),
                    ("checklist", "Чек-лист"),
                    ("comment", "Комментарий"),
                    ("external_link", "Ссылка"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BoardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "boards",
                    models.ManyToManyField(blank=True, to="nadein_board.taskboard"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создал задачу"),
                            ("updated", "Обновил задачу"),
                            ("claimed", "Взял задачу в работу"),
                            ("moved", "Переместил задачу"),
                            ("linked", "Связал объект"),
                            ("unlinked", "Убрал связь"),
                            ("attachment_added", "Добавил файл"),
                            ("attachment_removed", "Удалил файл"),
                            ("checklist_item_added", "Добавил пункт чек-листа"),
                            ("checklist_item_updated", "Изменил пункт чек-листа"),
                            ("checklist_item_completed", "Выполнил пункт чек-листа"),
                            (
                                "checklist_item_reopened",
                                "Вернул пункт чек-листа в работу",
                            ),
                            ("checklist_item_removed", "Удалил пункт чек-листа"),
                            ("comment_added", "Добавил комментарий"),
                            ("comment_edited", "Изменил комментарий"),
                            ("comment_removed", "Удалил комментарий"),
                        ],
                        max_length=32,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "object_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("external_link", "Внешняя ссылка"),
                            ("checklist_item", "Пункт чек-листа"),
                            ("comment", "Комментарий"),
                        ],
                        max_length=32,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="ID объекта"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nb_task_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="nadein_board.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "История задачи",
                "verbose_name_plural": "История задач",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TaskAutomation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "Событие"),
                            ("schedule", "Срок"),
                            ("button", "Кнопка"),
                        ],
                        default="event",
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Ручной запуск"),
                            ("task_created", "Задача создана"),
                            ("task_updated", "Задача изменена"),
                            ("task_moved", "Задача перемещена"),
                            ("label_added", "Метка добавлена"),
                            ("label_removed", "Метка удалена"),
                            ("assignee_changed", "Исполнитель изменён"),
                            ("due_date_changed", "Срок изменён"),
                            ("priority_changed", "Срочность изменена"),
                            ("attachment_added", "Файл добавлен"),
                            ("comment_added", "Комментарий добавлен"),
                            ("checklist_completed", "Пункт чек-листа выполнен"),
                            ("linked_object_added", "Связанный объект добавлен"),
                            ("date_reached", "Наступила дата"),
                        ],
                        default="task_updated",
                        max_length=32,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(blank=True, default=dict, verbose_name="Условия"),
                ),
                (
                    "actions",
                    models.JSONField(blank=True, default=list, verbose_name="Действия"),
                ),
                (
                    "schedule_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Настройки срока"
                    ),
                ),
                (
                    "applies_to_all_boards",
                    models.BooleanField(default=True, verbose_name="Для всех досок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "stop_on_error",
                    models.BooleanField(
                        default=True, verbose_name="Остановить при ошибке"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний запуск"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "boards",
                    models.ManyToManyField(
                        blank=True,
                        related_name="automations",
                        to="nadein_board.taskboard",
                        verbose_name="Доски",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nb_created_task_automations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автоматизация задач",
                "verbose_name_plural": "Автоматизации задач",
                "ordering": ["kind", "position", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskAutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=16, verbose_name="Источник")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("success", "Выполнено"),
                            ("partial", "Выполнено частично"),
                            ("failed", "Ошибка"),
                            ("skipped", "Пропущено"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Ключ идемпотентности"
                    ),
                ),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="Контекст"),
                ),
                (
                    "actions_log",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Журнал действий"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начато"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nb_task_automation_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запустил",
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="nadein_board.taskautomation",
                        verbose_name="Автоматизация",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_runs",
                        to="nadein_board.task",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "trigger_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_runs",
                        to="nadein_board.taskactivity",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запуск автоматизации задач",
                "verbose_name_plural": "Запуски автоматизаций задач",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TaskExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048, verbose_name="Ссылка")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nb_created_task_external_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="nadein_board.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Внешняя ссылка задачи",
                "verbose_name_plural": "Внешние ссылки задач",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="taskcover",
            name="external_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nadein_board.taskexternallink",
            ),
        ),
        migrations.CreateModel(
            name="BoardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nadein_board.taskboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "board"), name="nb_unique_board_preference"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(
                fields=["task", "-created_at"], name="nadein_boar_task_id_e5832c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskautomation",
            index=models.Index(
                fields=["kind", "is_active", "position"],
                name="nadein_boar_kind_32fb19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskautomation",
            index=models.Index(
                fields=["trigger", "is_active"], name="nadein_boar_trigger_82103b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskautomationrun",
            index=models.Index(
                fields=["automation", "-started_at"],
                name="nadein_boar_automat_16e40a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskautomationrun",
            index=models.Index(
                fields=["task", "-started_at"], name="nadein_boar_task_id_a9bada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskautomationrun",
            index=models.Index(
                fields=["status", "-started_at"], name="nadein_boar_status_10aab1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskexternallink",
            index=models.Index(
                fields=["task", "created_at"], name="nadein_boar_task_id_ff0d09_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskexternallink",
            constraint=models.UniqueConstraint(
                fields=("task", "url"), name="nb_uniq_task_external_link"
            ),
        ),
    ]
